### ISSUE TITLE
tests issue 

### ISSUE THREAD

**Issue by AhmedHelalAhmed** [LaravelDaily/Laravel-Challenge-Cleanup-Routes#1]
I have tests issues for example: 

1) Tests\Feature\AdminBooksRoutesTest::testUserAndGuestCannotAccessAdminDashboardPage
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "reviews" add column "rating" integer not null)

Caused by
PDOException: SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL

2) Tests\Feature\AdminBooksRoutesTest::testAdminUserCanAccessAdminDashboardPage
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "reviews" add column "rating" integer not null)

**Comment by PovilasKorop** [comment]
@AhmedHelalAhmed I think I've fixed it: https://github.com/LaravelDaily/Laravel-Challenge-Cleanup-Routes/commit/60fb9b5a86ba2c5cd816e4efdeae681a953bad86
But it is working on my computer, so can't test, can you test it?

**Comment by AhmedHelalAhmed** [comment]
@PovilasKorop I faced some other issues and fixed in https://github.com/LaravelDaily/Laravel-Challenge-Cleanup-Routes/pull/3
in the same way, you fixed the above now all tests passed in my first pull request https://github.com/LaravelDaily/Laravel-Challenge-Cleanup-Routes/pull/2

**Comment by JustinByrne** [comment]
I can confirm that I received the same issue even after the updated commit. I used @AhmedHelalAhmed #3 to fix and it worked.

**Comment by PovilasKorop** [comment]
@JustinByrne thanks for pointing the exact fix to merge, merged it just now

**Comment by mhyeganeh** [comment]
Hello and thanks for all of your valuable efforts.

I get an SQLSTATE[42000] error while executing migrations and I beleive it's related to this issue and merged PR.

So I just sent new PR (#31) that beleive fixes this issue.

screenshot:
![Annotation 2021-09-02 192320](https://user-images.githubusercontent.com/32367934/131868135-308dfed1-de74-4eb6-9a20-3b4aa3d03001.jpg)
